// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egxyomwszaiimukfcvro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVneHlvbXdzemFpaW11a2ZjdnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODc4NjUsImV4cCI6MjA3MDA2Mzg2NX0.mTcP7U3aK3qzH2h9aKCG74gegIiQLnqOlLAdq2_jXug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});